# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Trip.destroy_all
Comment.destroy_all
User.destroy_all
Subscription.destroy_all
Destination.destroy_all


subscription1 = Subscription.create(sub_type: "solo")
subscription2 = Subscription.create(sub_type: "group")

user1 = User.create(first_name: "Luka", last_name: "Baramishvili", email: "test1@test.com", username: "Lukab", subscription_id: subscription1.id, password:"123")


destination1 = Destination.create(price: 100, location:"Berlin, Germany", description:"Berlin, Germany’s capital, dates to the 13th century. Reminders of the city's turbulent 20th-century history include its Holocaust memorial and the Berlin Wall's graffitied remains. Divided during the Cold War, its 18th-century Brandenburg Gate has become a symbol of reunification. The city's also known for its art scene and modern landmarks like the gold-colored, swoop-roofed Berliner Philharmonie, built in 1963.", image: "https://www.roadaffair.com/wp-content/uploads/2018/01/aerial-view-berlin-germany-shutterstock_337203833-1024x664.jpg", timeframe:"07/20/2020 - 07/23/2020")
destination2 = Destination.create(price: 100, location:"Barcelona, Spain", description:"Barcelona, the cosmopolitan capital of Spain’s Catalonia region, is known for its art and architecture. The fantastical Sagrada Família church and other modernist landmarks designed by Antoni Gaudí dot the city. Museu Picasso and Fundació Joan Miró feature modern art by their namesakes. City history museum MUHBA, includes several Roman archaeological sites.", image: "https://img1.10bestmedia.com/Images/Photos/378847/GettyImages-1085317916_54_990x660.jpg", timeframe:"08/20/2020 - 08/23/2020")
destination3 = Destination.create(price: 100, location:"Lisbon, Portugal", description:"Lisbon is Portugal’s hilly, coastal capital city. From imposing São Jorge Castle, the view encompasses the old city’s pastel-colored buildings, Tagus Estuary and Ponte 25 de Abril suspension bridge. Nearby, the National Azulejo Museum displays 5 centuries of decorative ceramic tiles. Just outside Lisbon is a string of Atlantic beaches, from Cascais to Estoril.", image: "https://data.jigsawpuzzle.co.uk/castorland.21/lisbon-trams-portugal-jigsaw-puzzle-1000-pieces.65587-1.fs.jpg", timeframe:"09/15/2020 - 09/19/2020")
destination4 = Destination.create(price: 100, location:"Paris, France", description:"Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré.", image: "https://en.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/tour-eiffel-trocadero-630x405-c-thinkstock/37221-1-fre-FR/Tour-Eiffel-Trocadero-630x405-C-Thinkstock.jpg", timeframe:"10/15/2020 - 10/20/2020")
destination5 = Destination.create(price: 100, location:"Prague, Czech Republic", description:"Prague, capital city of the Czech Republic, is bisected by the Vltava River. Nicknamed “the City of a Hundred Spires,” it's known for its Old Town Square, the heart of its historic core, with colorful baroque buildings, Gothic churches and the medieval Astronomical Clock, which gives an animated hourly show. Completed in 1402, pedestrian Charles Bridge is lined with statues of Catholic saints.", image: "https://cdn.anadventurousworld.com/wp-content/uploads/2019/01/where-to-stay-in-prague.jpg", timeframe:"11/9/2020 - 11/13/2020")
destination6 = Destination.create(price: 100, location:"Reykjavic, Iceland", description:"Reykjavik, on the coast of Iceland, is the country's capital and largest city. It's home to the National and Saga museums, tracing Iceland’s Viking history. The striking concrete Hallgrimskirkja church and rotating Perlan glass dome offer sweeping views of the sea and nearby hills. Exemplifying the island’s volcanic activity is the geothermal Blue Lagoon spa, near the village of Grindavik.", image: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/04/03/21/image001.png", timeframe:"12/4/2020 - 12/7/2020")
destination7 = Destination.create(price: 100, location:"London, England", description:"London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. Across the Thames River, the London Eye observation wheel provides panoramic views of the South Bank cultural complex, and the entire city.", image: "https://img.theculturetrip.com/768x432/wp-content/uploads/2017/01/aerial-panoramic-cityscape-view-of-london-and-the-river-thames-england-united-kingdom-shutterstock_551334580.jpg", timeframe:"1/10/2020 - 1/10/2020")
destination8 = Destination.create(price: 100, location:"Amsterdam, Netherlands", description:"Amsterdam is the Netherlands’ capital, known for its artistic heritage, elaborate canal system and narrow houses with gabled facades, legacies of the city’s 17th-century Golden Age. Its Museum District houses the Van Gogh Museum, works by Rembrandt and Vermeer at the Rijksmuseum, and modern art at the Stedelijk. Cycling is key to the city’s character, and there are numerous bike paths.", image: "http://www.netherlands-tourism.com/wp-content/uploads/2019/02/ccimage-shutterstock_534783616.jpg", timeframe:"2/21/2021 - 2/24/2021")
destination9 = Destination.create(price: 100, location:"Tbilisi, Georgia", description:"Tbilisi is the capital of the country of Georgia. Its cobblestoned old town reflects a long, complicated history, with periods under Persian and Russian rule. Its diverse architecture encompasses Eastern Orthodox churches, ornate art nouveau buildings and Soviet Modernist structures. Looming over it all are Narikala, a reconstructed 4th-century fortress, and Kartlis Deda, an iconic statue of the “Mother of Georgia.”", image: "https://georgia.travel/files/image/2017-10-30/400X360/10004.jpg", timeframe:"2/17/2021 - 2/20/2021")
destination10 = Destination.create(price: 100, location:"Brussels, Belgium", description:"Belgium, a country in Western Europe, is known for medieval towns, Renaissance architecture and as headquarters of the European Union and NATO. The country has distinctive regions including Dutch-speaking Flanders to the north, French-speaking Wallonia to the south and a German-speaking community to the east. The bilingual capital, Brussels, has ornate guildhalls at Grand-Place and elegant art-nouveau buildings.", image: "https://thumbs-prod.si-cdn.com/n9O8zFNp0Fa5MOUnj_uE2Px3-24=/fit-in/1600x0/https://public-media.si-cdn.com/filer/22/4c/224c22f5-7af3-4a8b-9cfe-2b9b53cfbf53/flower-carpet.jpg", timeframe:"3/10/2021 - 3/14/2021")
destination11 = Destination.create(price: 100, location:"Copenhagen, Denmark", description:"Copenhagen, Denmark’s capital, sits on the coastal islands of Zealand and Amager. It’s linked to Malmo in southern Sweden by the Öresund Bridge. Indre By, the city's historic center, contains Frederiksstaden, an 18th-century rococo district, home to the royal family’s Amalienborg Palace. Nearby is Christiansborg Palace and the Renaissance-era Rosenborg Castle, surrounded by gardens and home to the crown jewels.", image: "https://img.theculturetrip.com/768x432/wp-content/uploads/2017/02/shutterstock_244708048-frederiksberg-have.jpg", timeframe:"10/11/2020 - 10/14/2020")
destination12 = Destination.create(price: 100, location:"Marseille, France", description:"Marseille, a port city in southern France, has been a crossroads of immigration and trade since its founding by the Greeks circa 600 B.C. At its heart is the Vieux-Port (Old Port), where fishmongers sell their catch along the boat-lined quay. Basilique Notre-Dame-de-la-Garde is a Romanesque-Byzantine church. Modern landmarks include Le Corbusier’s influential Cité Radieuse complex and Zaha Hadid’s CMA CGM Tower.", image: "https://res.cloudinary.com/hzekpb1cg/image/upload/c_fill,h_410,w_800,f_auto/s3/public/prod/2019-02/Marseille.jpg", timeframe:"11/23/2020 - 11/27/2020")
destination13 = Destination.create(price: 100, location:"Athens, Greece", description:"Athens is the capital of Greece. It was also at the heart of Ancient Greece, a powerful civilization and empire. The city is still dominated by 5th-century BC landmarks, including the Acropolis, a hilltop citadel topped with ancient buildings like the colonnaded Parthenon temple. The Acropolis Museum, along with the National Archaeological Museum, preserves sculptures, vases, jewelry and more from Ancient Greece.", image: "https://whyathens.com/wp-content/uploads/2016/06/What-to-do-in-Athens-Plaka-820x410.jpg", timeframe:"07/17/2020 - 07/20/2020")
destination14 = Destination.create(price: 100, location:"Budapest, Hungary", description:"Budapest, Hungary’s capital, is bisected by the River Danube. Its 19th-century Chain Bridge connects the hilly Buda district with flat Pest. A funicular runs up Castle Hill to Buda’s Old Town, where the Budapest History Museum traces city life from Roman times onward. Trinity Square is home to 13th-century Matthias Church and the turrets of the Fishermen’s Bastion, which offer sweeping views.", image: "https://d12dkjq56sjcos.cloudfront.net/pub/media/wysiwyg/route-images/View-Of-Budapest-Day-Slider-Big-Bus-Tours.jpg", timeframe:"09/05/2020 - 09/09/2020")
destination15 = Destination.create(price: 100, location:"Milan, Italy", description:"Milan, a metropolis in Italy's northern Lombardy region, is a global capital of fashion and design. Home to the national stock exchange, it’s a financial hub also known for its high-end restaurants and shops. The Gothic Duomo di Milano cathedral and the Santa Maria delle Grazie convent, housing Leonardo da Vinci’s mural “The Last Supper,” testify to centuries of art and culture.", image: "https://www.accessmba.com/application/public/cache/event-milan-620x370.jpg", timeframe:"11/15/2020 - 11/18/2020")

trip1 = Trip.create(user_id: user1.id, destination_id: destination1.id)
